[platformio]
default_envs = esp32s3
src_dir = src
include_dir = include

[env:esp32s3]
platform = espressif32
board = esp32s3box
framework = arduino

; Cấu hình vi điều khiển 240MHz
board_build.f_cpu = 240000000L

; Cấu hình bộ nhớ S3 N16R8 (16MB Flash, 8MB PSRAM OPI)
board_build.arduino.memory_type = qio_opi
build_flags = 
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DCORE_DEBUG_LEVEL=3
	
	; Cấu hình liên kết thư viện cấu hình màn hình
	-DUSER_SETUP_LOADED=1
	-include lib/TFT_eSPI_config/User_Setup.h
	-DLV_CONF_INCLUDE_SIMPLE
	-DLV_LVGL_H_INCLUDE_SIMPLE
	-I include

; Các thư viện cốt lõi cần cài đặt
lib_deps = 
	bodmer/TFT_eSPI@^2.5.31
	lvgl/lvgl@^8.3.9
    
; Thiết lập tốc độ truyền Serial để Monitor
monitor_speed = 115200
upload_speed = 921600
